# COPIED FROM https://github.com/pagopa/azure-pipeline-templates/blob/master/templates/node-job-setup/template.yaml
# THIS IS A PATCHED VERSION THAT MAKES THE JOB COMPATIBLE WITH YARN3
# TODO: refactor to GitHub Actions

# Azure DevOps pipeline template used to setup the Node project:
# 1. checkout code
# 2. setup correct node version
# 3. install node dependencies

parameters:

# the branch, tag or commit to checkout
- name: 'gitReference'
  type: string
  default: 'none'

# whether code must be checked-out with persisted credentials
- name: 'persistCredentials'
  type: string
  default: false

# optional sub path where the project to be initialized is located. To be used on repository with multiple projects.
- name: 'projectDir'
  type: string
  default: '.' # current folder is default

# if not set, the Node version will be red from .node-version and -nvmrc files, in this order
- name: 'nodeVersion'
  type: string
  default: 'none'

steps:
- checkout: self
  displayName: 'Checkout'
  persistCredentials: ${{ parameters.persistCredentials }}

# This is needed because the pipeline may point to a different commit than expected
# The common case is when the previous stage pushed another commit
- ${{ if ne(parameters.gitReference, 'none') }}:
  - bash: |
      git fetch && git checkout ${{ parameters.gitReference }}
    displayName: 'Checkout reference'

- bash: |
    cd ${{ parameters.projectDir }}
    echo "current folder: $(pwd)"
  displayName: 'Move to project folder'

# If a Node version is defined explicitly by parameter, such version is used
# Else, version is red from .node-version file
# Else, version is red from .nvmrc file
- ${{ if ne(parameters.nodeVersion, 'none') }}:
  - bash: |
      echo "current folder: $(pwd)"
      FROM_PARAM=${{ parameters.nodeVersion }}
      echo "set FROM_PARAM='$FROM_PARAM'"
      echo "##vso[task.setvariable variable=NODE_VERSION]$FROM_PARAM"
    workingDirectory: ${{ parameters.projectDir }}
    displayName: 'Determine Node.js version from template param'
- ${{ if eq(parameters.nodeVersion, 'none') }}:
  - bash: |
      echo "current folder: $(pwd)"
      FROM_SOURCE=$(cat .node-version || cat .nvmrc)
      ls .node-version && echo ".node-version found, value: '$(cat .node-version)'" || echo ".node-version not found"
      ls .nvmrc && echo ".nvmrc found, value: '$(cat .nvmrc)'" || echo ".nvmrc not found"
      echo "set FROM_SOURCE='$FROM_SOURCE'"
      echo "##vso[task.setvariable variable=NODE_VERSION]$FROM_SOURCE"
    workingDirectory: ${{ parameters.projectDir }}
    displayName: 'Determine Node.js version from source'

- task: UseNode@1
  inputs:
    version: $(NODE_VERSION)
  displayName: 'Set up Node.js'

- bash: |
    echo "current folder: $(pwd)"
    yarn --immutable
  workingDirectory: ${{ parameters.projectDir }}
  displayName: 'Install node modules'