# .github/workflows/chromatic.yml

# Workflow name
# https://www.chromatic.com/docs/github-actions
name: 'Chromatic'

# Event for the workflow
on:
  pull_request:
    types: [opened, ready_for_review, review_requested, reopened]

# List of jobs
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    # Ignore draft pull request
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@f191a0224b10e1a38b2091cefb7b7a2337009116 # v16.0.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          skip: 'dependabot/*|renovate/*|release/*|hotfix/*'
          autoAcceptChanges: 'main'
