name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-cd
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  js_code_review:
    # Ignore draft pull request and pull request opened from branch below
    if: |
      github.event.pull_request.draft == false &&
      !startsWith(github.head_ref, 'renovate/') &&
      !startsWith(github.head_ref, 'dependabot') &&
      !startsWith(github.head_ref, 'release/') &&
      !startsWith(github.head_ref, 'hotfix/') &&
      !startsWith(github.head_ref, 'main')
    runs-on: ubuntu-24.04
    steps:
      - name: Check-out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: .

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Check Build Size
        uses: ./.github/workflows/actions/build-size
        with:
          path: 'dist'
          max_raw_kb: '800'
          max_gzip_kb: '330'

      # - name: Unit tests exec
      #   run: yarn test:coverage

      # Codecov provides reports and metrics about test coverage data.
      # To enable set CODECOV_TOKEN secret at repo level and make sure
      # that your "code-review" script creates a "coverage/" folder in
      # the root workspace.
      #- name: Upload coverage report to codecov.io
      #  env:
      #    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #  if: ${{ env.CODECOV_TOKEN != '' }}
      #  uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
      #  with:
      #    token: ${{ env.CODECOV_TOKEN }}

      # The following job will be executed only if CODECOV_TOKEN is not set
      #- name: Code coverage
      #  env:
      #    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #  if: ${{ env.CODECOV_TOKEN == '' }}
      #  run: bash <(curl -s https://codecov.io/bash)
